In [1]:
import numpy as np

In [13]:
N = 8192

A = np.random.random((N, N)).astype(np.float32)
B = np.random.random((N, N)).astype(np.float32)

C = A @ B

print(C)

[[2022.0902 2057.2764 2051.4507 ... 2015.5394 2020.5918 2033.3157]
 [2042.06   2059.5034 2066.8706 ... 2031.5669 2045.2524 2058.7104]
 [2050.4885 2068.7136 2048.8328 ... 2040.3611 2042.9727 2039.723 ]
 ...
 [2015.4171 2047.8795 2045.469  ... 2006.2888 2016.3448 2022.7139]
 [2039.063  2037.867  2040.6936 ... 2024.2001 2016.3317 2042.1473]
 [2038.1376 2083.1384 2066.9739 ... 2045.7881 2041.0947 2064.2637]]
